"""change recommendation to jsonb

Revision ID: 41aeed6c5b1b
Revises: 49a20d347c37
Create Date: 2026-08-10 21:02:32.109406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41aeed6c5b1b'
down_revision: Union[str, Sequence[str], None] = '49a20d347c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disease_detections', 'recommendation',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='recommendation::jsonb',
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disease_detections', 'recommendation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
