"""change recommendation to text

Revision ID: 49a20d347c37
Revises: bfee34608779
Create Date: 2026-08-10 20:53:34.318879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49a20d347c37'
down_revision: Union[str, Sequence[str], None] = 'bfee34608779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease_knowledge')
    op.alter_column('disease_detections', 'recommendation',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'source',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_knowledge_documents_title'), 'knowledge_documents', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_documents_title'), table_name='knowledge_documents')
    op.alter_column('knowledge_documents', 'source',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('disease_detections', 'recommendation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               nullable=False)
    op.create_table('disease_knowledge',
    sa.Column('crop_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('disease_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('symptoms', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('treatment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('disease_knowledge_pkey'))
    )
    # ### end Alembic commands ###
