"""add disease knowledge vector table

Revision ID: 9529a10ecf85
Revises: bb6caaf2a6fe
Create Date: 2026-08-01 21:27:11.964649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9529a10ecf85'
down_revision: Union[str, Sequence[str], None] = 'bb6caaf2a6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
