"""add location to disease_detections

Revision ID: 960234c4d178
Revises: fa39e204974a
Create Date: 2026-08-14 16:33:49.428006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960234c4d178'
down_revision: Union[str, Sequence[str], None] = 'fa39e204974a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disease_detections', sa.Column('location', sa.String(length=255), nullable=True))
    # op.alter_column('disease_detections', 'recommendation',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=1000),
    #            existing_nullable=False)
    # op.alter_column('knowledge_documents', 'source',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=False)
    # op.drop_index(op.f('ix_knowledge_documents_title'), table_name='knowledge_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_knowledge_documents_title'), 'knowledge_documents', ['title'], unique=False)
    op.alter_column('knowledge_documents', 'source',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('disease_detections', 'recommendation',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('disease_detections', 'location')
    # ### end Alembic commands ###
